name: Push to GitHub Pages on push to main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@main
        env:
          HUGO_VERSION: 0.111.0
          TARGET_REPO: git@github.com:bimawa/diamondrill.github.io.git
          TARGET_BRANCH: main
          # TOKEN: ${{ secrets.TOKEN }}
          # HUGO_ARGS: '-t academic'
          CNAME: diamandrill.ru
